name: CI/CD for Frontend & Backend

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: DOCKER_USERNAME
          password: DOCKER_PASSWORD

      - name: Build & push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: DOCKER_USERNAME /front:latest

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: DOCKER_USERNAME
          password: DOCKER_PASSWORD

      - name: Build & push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./express
          file: ./express/Dockerfile
          push: true
          tags: DOCKER_USERNAME/express:latest
